version: '3.3'
services:
  go:
    build: .
    depends_on:
    - mysql
    environment:
      MYSQL: "true"
      MYSQL_HOST: mysql
      MYSQL_DATABASE: apiDatabase
      MYSQL_USER: user
      MYSQL_PASS: 1234
      MYSQL_PORT: 3306
    volumes:
    - ./src/:/src/
    ports:
    - "3000:80"
  mysql:
    image: 'mysql:5.6'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: apiDatabase
    ports:
    - "32826:3306"
    command: mysqld --user=root
    volumes:
      - ./database:/docker-entrypoint-initdb.d
